version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-${COOLIFY_CONTAINER_NAME:-local}-${RANDOM_ID:-001}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-oficina_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "coolify.managed=true"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-${COOLIFY_CONTAINER_NAME:-local}-${RANDOM_ID:-001}
    environment:
      - FLASK_ENV=production
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres123}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB:-oficina_db}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
      - CORS_ORIGINS=https://${COOLIFY_FQDN:-localhost},http://localhost:3000
    # Remover mapeamento de porta para Coolify
    expose:
      - "5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    labels:
      - "coolify.managed=true"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.coolify
      args:
        - Pass=${Pass:-}
    container_name: frontend-${COOLIFY_CONTAINER_NAME:-local}-${RANDOM_ID:-001}
    environment:
      - REACT_APP_API_URL=https://${COOLIFY_FQDN:-localhost}
      - REACT_APP_BACKEND_URL=https://${COOLIFY_FQDN:-localhost}
      - Pass=${Pass:-}
    # Remover mapeamento de porta para Coolify
    expose:
      - "7080"
    depends_on:
      - backend
    networks:
      - app-network
    labels:
      - "coolify.managed=true"

  nginx:
    image: nginx:alpine
    container_name: nginx-${COOLIFY_CONTAINER_NAME:-local}-${RANDOM_ID:-001}
    volumes:
      - ./nginx/nginx.coolify.conf:/etc/nginx/nginx.conf:ro
    # Mapeamento de porta para acesso local
    ports:
      - "7080:80"
    expose:
      - "80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=erp-oficina-nginx"
      # Labels do Traefik para roteamento automático
      - "traefik.enable=true"
      - "traefik.http.routers.erp-oficina.rule=Host(`${COOLIFY_FQDN:-oficina.onlitec.com.br}`)"
      - "traefik.http.routers.erp-oficina.tls=true"
      - "traefik.http.routers.erp-oficina.tls.certresolver=letsencrypt"
      - "traefik.http.services.erp-oficina.loadbalancer.server.port=80"

volumes:
  postgres_data:
    labels:
      - "coolify.managed=true"

networks:
  app-network:
    driver: bridge
    labels:
      - "coolify.managed=true"